const names = [
  "eletrônicos",
  "livros",
  "ferramentas",
  "brinquedos",
  "roupas",
  "calçados",
  "móveis",
  "esportes",
  "beleza",
  "automóveis",
  "instrumentos",
  "jogos",
  "cosméticos",
  "joias",
  "acessórios",
  "eletrodomésticos",
  "informática",
  "telefonia",
  "papelaria",
  "decoração",
  "pet",
  "construção",
  "jardinagem",
  "bebidas",
  "alimentos",
  "viagens",
  "fitness",
  "hobbies",
  "colecionáveis",
  "fotografia",
  "video games",
  "relógios",
  "saúde",
  "bebês",
  "lazer",
  "segurança",
  "som e áudio",
  "câmeras",
  "bicicletas",
  "moto peças",
  "carro peças",
  "mercado",
  "orgânicos",
  "iluminação",
  "automação",
  "software",
  "hardware",
  "equipamentos médicos",
  "produtos veterinários",
  "utensílios domésticos",
  "produtos de limpeza",
  "materiais escolares",
  "produtos de escritório",
  "brindes",
  "presentes",
  "artesanato",
  "festas",
  "música",
  "produtos naturais",
  "produtos importados",
  "produtos de luxo",
  "coleções exclusivas",
  "ecológicos",
  "vegan",
  "produtos para idosos",
  "cosméticos naturais",
  "produtos sustentáveis",
  "produtos regionais",
  "super alimentos",
  "produtos gourmet",
  "suplementos",
  "emagrecimento",
  "cuidados pessoais",
  "acessibilidade",
  "serviços",
  "assessoria",
  "consultoria",
  "treinamento",
  "educação",
  "livraria",
  "material esportivo",
  "esportes radicais",
  "pesca",
  "caça",
  "camping",
  "viagens",
  "turismo",
  "gastronomia",
  "vinhos",
  "cervejas artesanais",
  "destilados",
  "chás",
  "cafés",
  "chocolates",
  "doces",
  "salgados",
  "culinária",
  "decoração de festas",
  "panificação",
  "confeitaria",
  "tatuagem",
  "piercing",
  "cuidados com a pele",
  "estética",
  "manicure",
  "pedicure",
  "cabeleireiro",
  "maquiagem",
  "roupas íntimas",
  "lingerie",
  "pijamas",
  "moda praia",
  "moda fitness",
  "moda casual",
  "moda social",
  "moda infantil",
  "moda masculina",
  "moda feminina",
  "moda plus size",
  "moda sustentável",
  "sapatos",
  "bolsas",
  "malas",
  "mochilas",
  "equipamentos esportivos",
  "gadgets",
  "smart home",
  "wearables",
  "drones",
  "robótica",
  "programação",
  "design",
  "arte",
  "pintura",
  "escultura",
  "fotografia",
  "edição de vídeo",
  "produção de música",
  "streaming",
  "podcasts",
  "publicação",
  "escrita",
  "livros digitais",
  "audiolivros",
  "cursos online",
  "aulas particulares",
  "tutoria",
  "mentoria",
  "coaching",
  "psicologia",
  "terapia",
  "nutrição",
  "dietética",
  "fisioterapia",
  "pilates",
  "yoga",
  "meditação",
  "mindfulness",
  "astrologia",
  "esoterismo",
  "tarot",
  "religião",
  "espiritualidade",
  "autoajuda",
  "bem-estar",
  "relaxamento",
  "massagem",
  "terapias alternativas",
  "flores",
  "plantas",
  "horticultura",
  "paisagismo",
  "decoração de interiores",
  "organização",
  "feng shui",
  "minimalismo",
  "viagens de aventura",
  "mochilão",
  "cruzeiros",
  "passeios de barco",
  "esportes aquáticos",
  "mergulho",
  "natação",
  "remo",
  "canoagem",
  "vela",
  "pesca esportiva",
  "esqui",
  "snowboard",
  "patinação no gelo",
  "escalada",
  "alpinismo",
  "trilhas",
  "ciclismo",
  "motocross",
  "kart",
];

export const generateRandomName = () => {
  const randomIndex = Math.floor(Math.random() * names.length);
  return names[randomIndex];
};
